// export constant
export {TABLE_RESIZE, CHANGE_TEXT, APPLY_STILE, CHANGE_STYLES, CHANGE_TITLE};

const TABLE_RESIZE = 'TABLE_RESIZE';
const CHANGE_TEXT = 'CHANGE_TEXT';
const APPLY_STILE = 'APPLY_STILE';
const CHANGE_STYLES = 'CHANGE_STYLES';
const CHANGE_TITLE = 'CHANGE_TITLE';
